[package]
name = "markwriter"
version = "2.0.0-alpha.1"
description = "A modern Markdown editor built with Tauri"
authors = ["Richie Eiger <rheiger@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0" }

[dependencies]
tauri = { version = "2.0", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "markwriter"
path = "src/main.rs"
