name: Build macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Generate app icon
        run: |
          python tools/generate_icon.py

      - name: Build app with PyInstaller
        run: |
          pyinstaller -y MarkWrite.spec

      - name: Prepare zip name
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "ZIP_NAME=MarkWrite-$VERSION-macOS.zip" >> "$GITHUB_ENV"

      - name: Zip app
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/MarkWrite.app "dist/${ZIP_NAME}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: dist/${{ env.ZIP_NAME }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/${{ env.ZIP_NAME }}
          generate_release_notes: true
