name: Build Desktop Apps

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Generate app icon
        run: |
          python tools/generate_icon.py

      - name: Build app with PyInstaller
        run: |
          pyinstaller -y MarkWrite.spec

      - name: Prepare zip name
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "ZIP_NAME=MarkWrite-$VERSION-macOS.zip" >> "$GITHUB_ENV"

      - name: Zip app
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/MarkWrite.app "dist/${ZIP_NAME}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: dist/${{ env.ZIP_NAME }}

      - name: Publish GitHub Release (macOS)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/${{ env.ZIP_NAME }}
          generate_release_notes: true

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Build app with PyInstaller (Windows)
        run: |
          pyinstaller -y MarkWrite-win.spec

      - name: Zip app
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "ZIP_NAME=MarkWrite-$VERSION-windows.zip" >> "$GITHUB_ENV"
          7z a -tzip "dist/${ZIP_NAME}" dist/MarkWrite/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: dist/${{ env.ZIP_NAME }}

      - name: Publish GitHub Release (Windows)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/${{ env.ZIP_NAME }}
          generate_release_notes: true

  build-linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxkbcommon0 libxrender1 libxext6 libx11-6 libdbus-1-3 libglib2.0-0 libxcomposite1 libxi6 libxcursor1 libxdamage1 libxtst6 libnss3 libasound2

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Build app with PyInstaller (Linux)
        run: |
          pyinstaller -y MarkWrite-linux.spec

      - name: Zip app
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "ZIP_NAME=MarkWrite-$VERSION-linux.zip" >> "$GITHUB_ENV"
          cd dist && zip -r "${ZIP_NAME}" MarkWrite

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: dist/${{ env.ZIP_NAME }}

      - name: Publish GitHub Release (Linux)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/${{ env.ZIP_NAME }}
          generate_release_notes: true
